board_game:
  name: gomoku
  m: 8 
  n: 9
  k: 5
  cell_size: 40
  fps: 5
  menu_font_size: 30
  button_font_size: 18 
  symbol_font_size: 40
bot:
  algorithm: mcts
  config:
    max_thinking_time: 5.0  # in seconds
    max_rollout: 1000000000
    processes: 8  # number of processes
    policy: simple
    exploration_const: 1.4142135623730951
    num_simulations: 64
